---
# Test playbook to trigger incident creation for an unreachable device

- name: Test ServiceNow Integration with Failed Device
  hosts: localhost
  gather_facts: yes
  
  vars:
    # ServiceNow connection from vault
    servicenow_host: "{{ vault_servicenow_host }}"
    servicenow_username: "{{ vault_servicenow_username }}"
    servicenow_password: "{{ vault_servicenow_password }}"
    
    # Default incident parameters from vault
    servicenow_default_caller: "{{ vault_servicenow_default_caller }}"
    servicenow_default_assignment_group: "{{ vault_servicenow_default_assignment_group }}"
    
    # Simulate a network device
    inventory_hostname: "failed-device-01"
    ansible_host: "192.168.99.99"
    device_type: "cisco_ios"
    device_location: "Building 99"
    
  tasks:
    - name: Simulate device uptime check that will fail
      block:
        - name: Force a failure to trigger rescue block
          ansible.builtin.fail:
            msg: "Device unreachable - Connection timeout"
            
      rescue:
        - name: Create ServiceNow incident for connectivity failure
          include_role:
            name: servicenow_incident_creator
          vars:
            incident_short_description: "[NETWORK] Device {{ inventory_hostname }} unreachable"
            incident_description: |
              Network Device Connectivity Failure
              
              Device Details:
              - Hostname: {{ inventory_hostname }}
              - IP Address: {{ ansible_host }}
              - Device Type: {{ device_type }}
              - Location: {{ device_location }}
              
              Failure Information:
              - Check Type: ICMP Ping Test
              - Timeout: 10s
              - Failed Task: {{ ansible_failed_task.name }}
              - Error Message: {{ ansible_failed_result.msg }}
              
              Impact:
              This device is not responding to network connectivity tests and may be offline,
              affecting network services and connected systems.
              
              Recommended Actions:
              1. Verify physical connectivity and power status
              2. Check upstream network devices
              3. Review recent configuration changes
              4. Check device logs if accessible via console
            incident_correlation_id: "device_connectivity_{{ inventory_hostname }}"
            incident_urgency: high
            incident_impact: high
            incident_assignment_group: "{{ servicenow_default_assignment_group }}"
            incident_category: network
            incident_subcategory: connectivity
            incident_work_notes: "Automated detection by Ansible health check"