---
# Test playbook to force incident creation

- name: Test ServiceNow Incident Creation
  hosts: localhost
  gather_facts: yes
  
  vars:
    # ServiceNow connection from vault
    servicenow_host: "{{ vault_servicenow_host }}"
    servicenow_username: "{{ vault_servicenow_username }}"
    servicenow_password: "{{ vault_servicenow_password }}"
    
    # Default incident parameters from vault
    servicenow_default_caller: "{{ vault_servicenow_default_caller }}"
    servicenow_default_assignment_group: "{{ vault_servicenow_default_assignment_group }}"
    
  tasks:
    - name: Force incident creation by simulating failed device check
      include_role:
        name: servicenow_incident_creator
      vars:
        incident_short_description: "[NETWORK] Device test-router-01 unreachable"
        incident_description: |
          Network Device Connectivity Failure
          
          Device Details:
          - Hostname: test-router-01
          - IP Address: 192.168.1.99
          - Device Type: cisco_ios
          - Location: Test Lab
          
          Failure Information:
          - Check Type: ICMP Ping Test
          - Timeout: 10s
          - Failed Task: Test device connectivity
          - Error Message: Connection timeout - no response from device
          
          Impact:
          This device is not responding to network connectivity tests and may be offline,
          affecting network services and connected systems.
          
          Recommended Actions:
          1. Verify physical connectivity and power status
          2. Check upstream network devices
          3. Review recent configuration changes
          4. Check device logs if accessible via console
        incident_correlation_id: "device_connectivity_test-router-01"
        incident_urgency: medium
        incident_impact: medium
        incident_assignment_group: "{{ servicenow_default_assignment_group }}"
        incident_category: network
        incident_subcategory: connectivity
        incident_work_notes: "Test incident created by Ansible automation"
        inventory_hostname: test-router-01
        ansible_host: 192.168.1.99
        device_type: cisco_ios
        device_location: "Test Lab"