---
all:
  children:
    network_devices:
      children:
        core_switches:
          hosts:
            core-sw-01:
              ansible_host: 10.1.1.1
              device_type: cisco_ios
              device_location: "Datacenter A"
              device_asset_tag: "P1000002"
            core-sw-02:
              ansible_host: 10.1.1.2
              device_type: cisco_ios
              device_location: "Datacenter A"
        
        access_switches:
          hosts:
            access-sw-01:
              ansible_host: 10.1.2.1
              device_type: cisco_ios
              device_location: "Building 1 Floor 1"
            access-sw-02:
              ansible_host: 10.1.2.2
              device_type: cisco_ios
              device_location: "Building 1 Floor 2"
        
        routers:
          hosts:
            edge-rtr-01:
              ansible_host: 10.1.3.1
              device_type: cisco_ios_xr
              device_location: "Datacenter Edge"
            edge-rtr-02:
              ansible_host: 10.1.3.2
              device_type: cisco_ios_xr
              device_location: "Datacenter Edge"
            external-rtr-01:
              ansible_host: 5.78.128.250
              ansible_user: "{{ vault_external_device_user }}"
              ansible_password: "{{ vault_external_device_password }}"
              ansible_connection: ssh
              device_type: linux
              device_location: "External Site"
  
  vars:
    ansible_network_os: ios
    ansible_connection: network_cli
    ansible_user: "{{ vault_network_user }}"
    ansible_password: "{{ vault_network_password }}"