---
all:
  children:
    # Group by device OS type for proper connection handling
    cisco_ios_devices:
      children:
        ios_core_switches:
          hosts:
            core-sw-01:
              ansible_host: 10.1.1.1
            core-sw-02:
              ansible_host: 10.1.1.2
        
        ios_access_switches:
          hosts:
            access-sw-01:
              ansible_host: 10.1.2.1
            access-sw-02:
              ansible_host: 10.1.2.2
    
    cisco_iosxr_devices:
      hosts:
        edge-rtr-01:
          ansible_host: 10.1.3.1
        edge-rtr-02:
          ansible_host: 10.1.3.2
    
    linux_devices:
      hosts:
        external-rtr-01:
          ansible_host: 5.78.128.250
    
    # Logical groupings for monitoring (reference the OS groups)
    network_devices:
      children:
        cisco_ios_devices:
        cisco_iosxr_devices:
    
    core_switches:
      children:
        ios_core_switches:
        
    access_switches:
      children:
        ios_access_switches:
        
    routers:
      children:
        cisco_iosxr_devices: