---
# ServiceNow connection configuration
servicenow_instance:
  host: "{{ servicenow_host }}"
  username: "{{ servicenow_username }}"
  password: "{{ servicenow_password }}"

# Default values for incident creation
servicenow_incident_defaults:
  caller: "{{ servicenow_default_caller | default(vault_servicenow_default_caller) | default('ansible.automation') }}"
  assignment_group: "{{ servicenow_default_assignment_group | default(vault_servicenow_default_assignment_group) | default('network.operations') }}"
  category: network
  subcategory: "{{ servicenow_default_subcategory | default('router') }}"

# CI association for network devices
servicenow_ci_lookup:
  enabled: true
  field: name  # Use CI name for lookup
  
# Duplicate prevention
servicenow_duplicate_check:
  enabled: true
  window_hours: 2  # Check for duplicates within last 2 hours

# API retry configuration
servicenow_api_retry:
  retries: 3
  delay: 5

# ServiceNow Field Requirements Documentation
# ============================================
#
# REQUIRED FIELDS (must be provided by caller):
# - incident_caller: ServiceNow user ID (e.g., 'admin', 'john.doe')
# - incident_short_description: Brief summary of the incident
#
# OPTIONAL FIELDS WITH DEFAULTS:
# - incident_description: Detailed description (default: 'Created by Ansible automation')
# - incident_urgency: low, medium, high (default: 'medium')
# - incident_impact: low, medium, high (default: 'medium')
# - incident_assignment_group: ServiceNow group name (default: from vault/defaults)
# - incident_category: ServiceNow category (default: 'network')
# - incident_subcategory: ServiceNow subcategory (default: from defaults)
#
# OPTIONAL FIELDS (empty if not provided):
# - incident_service: ServiceNow service
# - incident_service_offering: ServiceNow service offering  
# - incident_channel: How incident was reported
# - incident_assigned_to: Specific user assignment
# - incident_correlation_id: For duplicate prevention
# - incident_work_notes: Additional notes
# - incident_asset_tag: For CI association