---
# ServiceNow connection configuration
servicenow_instance:
  host: "{{ servicenow_host }}"
  username: "{{ servicenow_username }}"
  password: "{{ servicenow_password }}"

# Default values for incident creation
servicenow_incident_defaults:
  caller: "{{ servicenow_default_caller | default(vault_servicenow_default_caller) | default('ansible.automation') }}"
  assignment_group: "{{ servicenow_default_assignment_group | default(vault_servicenow_default_assignment_group) | default('network.operations') }}"
  category: network
  subcategory: "{{ servicenow_default_subcategory | default('router') }}"

# CI association for network devices
servicenow_ci_lookup:
  enabled: true
  field: name  # Use CI name for lookup
  
# Duplicate prevention
servicenow_duplicate_check:
  enabled: true
  window_hours: 2  # Check for duplicates within last 2 hours

# API retry configuration
servicenow_api_retry:
  retries: 3
  delay: 5