---
# Purpose: ServiceNow ITSM automation wrapper for incidents, changes, and problems
# Design Pattern: Multi-object ITSM handler with type-based routing and trusted time source

- name: Ensure localhost facts are available for trusted timestamps
  setup:
  delegate_to: localhost
  delegate_facts: true
  run_once: true

- name: Validate required ITSM type
  assert:
    that:
      - itsm_type is defined
      - itsm_type in ['incident', 'change', 'problem']
    fail_msg: "itsm_type is required and must be one of: incident, change, problem"

- name: Route to appropriate ITSM handler
  include_tasks: "{{ itsm_type }}.yml"