---
# Purpose: Handle network topology changes (new/removed interfaces) by creating ServiceNow problems
# Design Pattern: Topology change management with problem ticket creation for manual review

- name: Generate topology change problem content from templates
  set_fact:
    rendered_description: "{{ lookup('template', 'topology_change_description.j2') }}"
    rendered_work_notes: "{{ lookup('template', 'topology_change_work_notes.j2') }}"

- name: Create ServiceNow problem for network topology changes
  include_role:
    name: servicenow_itsm
  vars:
    itsm_type: problem
    problem_short_description: "[TOPOLOGY CHANGE] Interface changes detected on {{ inventory_hostname }}"
    problem_description: "{{ rendered_description }}"
    problem_work_notes: "{{ rendered_work_notes }}"
    problem_correlation_id: "topology_change_{{ inventory_hostname }}_{{ current_timestamp | hash('md5') }}"
    problem_urgency: "{{ interface_change_problem_urgency | default('medium') }}"
    problem_impact: "{{ interface_change_problem_impact | default('low') }}"
    problem_assignment_group: "{{ interface_change_assignment_group | default('network.operations') }}"
    problem_category: network
    problem_subcategory: configuration
    problem_state: new

- name: Log topology change problem created
  ansible.builtin.debug:
    msg: |
      Network topology change problem created for {{ inventory_hostname }}:
      - New interfaces: {{ interface_changes.new_interfaces | join(', ') if interface_changes.new_interfaces | length > 0 else 'None' }}
      - Removed interfaces: {{ interface_changes.removed_interfaces | join(', ') if interface_changes.removed_interfaces | length > 0 else 'None' }}
      - Problem number: {{ servicenow_problem_result.number | default('N/A') }}