---
# Purpose: Check device connectivity, create incidents for failures, and close them when resolved
# Design Pattern: Health check with state management for incident lifecycle

- name: Device connectivity check with incident lifecycle management
  block:
    - name: Test device connectivity
      ansible.builtin.ping:
        data: uptime_check
      register: ping_result
      timeout: "{{ uptime_check_timeout | default(10) }}"

    - name: Gather device facts if reachable
      ansible.builtin.setup:
        filter: 
          - ansible_uptime_seconds
          - ansible_net_model
          - ansible_net_version
      when: ping_result is succeeded

    - name: Log successful connectivity
      ansible.builtin.debug:
        msg: "Device {{ inventory_hostname }} is UP ({{ ansible_uptime_seconds | default('unknown') }}s uptime)"
      when: ping_result is succeeded

    - name: Generate incident closure content from templates
      set_fact:
        rendered_close_notes: "{{ lookup('template', 'connectivity_resolved_close_notes.j2') }}"
        rendered_close_work_notes: "{{ lookup('template', 'connectivity_resolved_work_notes.j2') }}"
      when: ping_result is succeeded

    - name: Close any open incidents for this device
      include_role:
        name: servicenow_itsm
        tasks_from: close_incident
      vars:
        incident_correlation_id: "device_connectivity_{{ inventory_hostname }}"
        incident_close_code: "Resolved by caller"
        incident_close_notes: "{{ rendered_close_notes }}"
        incident_close_work_notes: "{{ rendered_close_work_notes }}"
      when: ping_result is succeeded

  rescue:
    - name: Generate incident content from templates
      set_fact:
        rendered_description: "{{ lookup('template', 'connectivity_failure_description.j2') }}"
        rendered_work_notes: "{{ lookup('template', 'connectivity_failure_work_notes.j2') }}"

    - name: Create ServiceNow incident for connectivity failure
      include_role:
        name: servicenow_itsm
      vars:
        itsm_type: incident
        incident_caller: "{{ uptime_incident_caller | default(servicenow_default_caller) | default('ansible.automation') }}"
        incident_short_description: "[NETWORK] Device {{ inventory_hostname }} unreachable"
        incident_description: "{{ rendered_description }}"
        incident_work_notes: "{{ rendered_work_notes }}"
        incident_correlation_id: "device_connectivity_{{ inventory_hostname }}"
        incident_urgency: "{{ uptime_incident_urgency | default('medium') }}"
        incident_impact: "{{ uptime_incident_impact | default('medium') }}"
        incident_assignment_group: "{{ uptime_assignment_group | default('network.operations') }}"
        incident_category: network
        incident_subcategory: connectivity
        incident_asset_tag: "{{ device_asset_tag | default(omit) }}"