---
# Interface monitoring with ServiceNow incident management and diagnostic logs
- name: Network Interface Monitoring
  hosts: network_devices
  gather_facts: no
  
  vars:
    # Playbook scheduling configuration
    playbook_schedule:
      enabled: true
      schedule: "*/10 * * * *"  # Every 10 minutes (override role default of 15 min)
      description: "Interface status monitoring with diagnostic log collection"
      inventory_groups:
        - network_devices
        - core_switches
        - access_switches
  
  pre_tasks:
    - name: Ensure interface monitoring storage directory exists
      ansible.builtin.file:
        path: "{{ interface_monitoring_storage_path | default('/var/lib/ansible/interface-monitoring') }}"
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true
    
  tasks:
    - name: Run interface monitoring with log collection
      include_role:
        name: interface_monitoring
      tags:
        - monitoring
        - interfaces
        - servicenow
        - logs